# Application Information
name: RaxCare
description: A healthcare Flutter application providing patient care services.

# Prevents package from being published to pub.dev
publish_to: 'none'

# Application version and build number
# Format: version+buildNumber
version: 1.0.0+1

# Dart SDK constraints
environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # UI and Core Utilities
  cupertino_icons: ^1.0.6      # iOS-style icons
  google_fonts: ^5.1.0         # Custom font implementation
  font_awesome_flutter: ^10.8.0 # Extended icon set
  
  # Web and External Services
  webview_flutter: ^4.7.0      # Embedded web content
  url_launcher: ^6.2.6         # Launch URLs, phone calls, emails

  # Local Storage
  shared_preferences: ^2.0.8   # Persistent key-value storage

  # UI Enhancement Packages
  confetti: ^0.8.0             # Celebration effects
  lottie: ^2.3.2              # Animation player for Adobe After Effects
  percent_indicator: ^4.2.3    # Linear and circular progress indicators
  syncfusion_flutter_gauges: ^28.1.39 # Radial and linear gauges
  animated_text_kit: ^4.2.3    # Text animations
  introduction_screen: ^3.1.17 # Onboarding screens
  flutter_spinkit: ^5.2.0      # Loading indicators
  im_stepper: ^1.0.1           # Multi-step processes visualization
  flutter_map: ^6.1.0          # Map implementation
  flutter_animate: ^4.5.2      # Animation utilities
  glassmorphism: ^3.0.0        # Frosted glass UI effect
  shimmer: ^3.0.0              # Loading effect
  flutter_markdown: ^0.7.6+2

  # Authentication
  google_sign_in: ^6.2.0       # Google authentication
  google_generative_ai: ^0.4.6
  permission_handler: ^11.4.0
  flutter_svg: ^2.0.17

  syncfusion_flutter_charts: ^28.2.12


  # Firebase Services
  firebase_core: ^2.24.2       # Firebase core functionality
  firebase_auth: ^4.17.6       # Firebase authentication
  cloud_firestore: ^4.15.6     # Firebase cloud database

  # State Management
  provider: ^6.0.5             # Provider pattern implementation
  riverpod: ^2.5.1             # State management solution

# Development Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3        # Recommended linting rules

# Flutter Configuration
flutter:
  # Material Design
  uses-material-design: true

  # Application Assets
  assets:
    - assets/animations/welcome.json  # Welcome screen animation
    - assets/logo.png                # Application logo
    - assets/default_profile.png      # Default profile image
    - assets/animations/progress.json # Progress tracking animation
    - assets/animations/ai_analytics.json # AI analytics animation
    - assets/animations/recovery.json # Recovery process animation
    - assets/animations/register.json # Registration animation