name: fyp_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.7.0
  cupertino_icons: ^1.0.6

  shared_preferences: ^2.0.8
  confetti: ^0.8.0
  lottie: ^2.3.2
  url_launcher: ^6.2.6
  percent_indicator: ^4.2.3
  syncfusion_flutter_gauges: ^28.1.39
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.3

  # Firebase dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.6

  # Fixed provider version
  provider: ^6.0.5
  riverpod: ^2.5.1
  flutter_spinkit: ^5.2.0
  im_stepper: ^1.0.1
  flutter_map: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

assets:
  - assets/animations/celebration.json
